[tool.poetry]
name = "tube"
version = "0.6.4"
description = "Gen3 ETL Service"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/uc-cdis/tube"
include = [
  "NOTICE",
]

[tool.poetry.dependencies]
python = "^3.9"
cdislogging = "1.1.1"
cryptography = "^37.0.4"
dictionaryutils = "^3.0.2"
elasticsearch = "6.4.0"
elasticsearch-dsl = "6.4.0"
gdcdictionary = "1.2.0"
gen3datamodel = "3.0.2"
hdfs = "2.7.0"
psycopg2-binary="2.9.3"
psqlgraph = "3.0.1"
py2neo = "2021.2.3"
pyspark = "3.3.0"
requests = "^2.27.1"
setuptools = "65.3.0"
six = "1.16.0"
Werkzeug = "2.2.2"
ipaddress = "1.0.23"

[tool.poetry.dev-dependencies]
pytest="5.4.3"
pytest-cov="3.0.0"
codacy-coverage="^1.3.11"
mock="4.0.3"
moto="1.1.24"
pyspark-stubs="*"

[tool.poetry.scripts]
fence-create = 'bin.fence_create:main'

[build-system]
requires = ["setuptools=65.3.0","poetry>=1.1.0"]
build-backend = "poetry.masonry.api"